import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import Header from "@/components/header/Header";
import Player from "@/components/player/Player";
import { Sidebar } from "@/components/sidebar/Sidebar";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col h-screen">
            <Header />
            <ResizablePanelGroup
              direction="horizontal"
              className="flex-1 border-y"
            >
              <ResizablePanel defaultSize={20} minSize={5} maxSize={20}>
                <Sidebar />
              </ResizablePanel>
              <ResizableHandle withHandle />
              <ResizablePanel defaultSize={80}>
                <div className="h-full overflow-y-auto">{children}</div>
              </ResizablePanel>
            </ResizablePanelGroup>
            <Player />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
